// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using unikovahra.Server.Data;

#nullable disable

namespace unikovahra.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251213132935_Seedovani")]
    partial class Seedovani
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("unikovahra.Server.Models.MiniGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MiniGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "První minihra",
                            RoomId = 1,
                            Title = "Elektrický rozvaděč – Směřování energie"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Druhá minihra",
                            RoomId = 2,
                            Title = "Světelná kombinace – Otevření dveří"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Třetí minihra",
                            RoomId = 3,
                            Title = "Bankovní systém - Hackovací kódy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Čtvrtá minihra",
                            RoomId = 4,
                            Title = "Dolarová kombinace - Logická skládačka"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pátá minihra",
                            RoomId = 5,
                            Title = "Zamykací panel - Zastavení čísel"
                        });
                });

            modelBuilder.Entity("unikovahra.Server.Models.MinigameFinish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailureSubtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SuccessSubtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuccessTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MinigameFinishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FailureSubtitle = "Čas vypršel a systém selhal",
                            FailureText = "Nepodařilo se ti úkol dokončit včas. Čas vypršel, než ses stihl správně propojit všechny šipky a vytvořit souvislou trasu od startu do cíle. Nouzový okruh zůstal neaktivní, rozvaděč zůstal tichý a trezorové dveře zůstávají zamčené. Systém vyhodnotil neúspěch a všechny pokusy selhaly.\r\nTvá chyba má následky. Můžeš se pokusit minihru zahrát znovu, ale část tvých peněz bude odečtena jako pokuta za neúspěch, nebo se rozhodnout misi ukončit a opustit budovu bez dalšího postupu.",
                            FailureTitle = "Proud nezprovozněn",
                            RoomId = 1,
                            SuccessSubtitle = "Dveře se odblokovaly – máš volný průchod",
                            SuccessText = "Zbývá jen pár vteřin do vypršení času, když přesměruješ poslední směr na panelu. Celým nouzovým okruhem konečně proběhne plný proud. Rozvaděč hlasitě zavrčí a studená tma je náhle rozčíslena ostrým nouzovým světlem. Proud je zpět! Systém reaguje, mechanika se v trezorových dveřích uvolní a ty máš cestu ven volnou.",
                            SuccessTitle = "Proud Obnoven!"
                        },
                        new
                        {
                            Id = 2,
                            FailureSubtitle = "Dveře zůstávají zamčené a systém nereaguje",
                            FailureText = "Nepodařilo se ti dokončit sekvenci včas. Čas vypršel, než ses stihl trefit do všech správných tlačítek, nebo jsi omylem klikl na několik nesprávných tlačítek vedle. Mřížka zůstala neaktivní, elektronická pojistka se nezměnila a dveře do kanceláře ředitele zůstávají pevně zamčené. Systém vyhodnotil neúspěch a úkol nebyl splněn.\r\nNásledky jsou jasné: můžeš se pokusit minihru znovu zahrát, ale část tvých peněz bude odečtena, nebo se rozhodnout misi ukončit a vzdát další postup.",
                            FailureTitle = "Kombinace selhala",
                            RoomId = 2,
                            SuccessSubtitle = "Dveře odblokovány – vstup do kanceláře volný",
                            SuccessText = "Soustředěně dýcháš a dokončuješ poslední, nejdelší sekvenci. Tvé prsty se pohybují s přesností. Jakmile stiskneš poslední tlačítko správně, celá mřížka zazáří jasným, triumfálním zeleným světlem. Slyšíš tiché cvaknutí. Elektronická pojistka se uvolnila! Dveře do kanceláře ředitele se odemkly. Cesta k dalšímu, nezbytnému úkolu pro tvůj únik je volná.",
                            SuccessTitle = "Kombinace zadána úspěšně!"
                        },
                        new
                        {
                            Id = 3,
                            FailureSubtitle = "Kamery stále aktivní",
                            FailureText = "Nepodařilo se ti dokončit úkol včas. Čas vypršel, než ses stihl přesně opsat všechny blikající kódy, nebo jsi během přepisování udělal chybu. Obraz na kamerách zůstal aktivní a kontrolky signalizují, že sledování stále běží. Alarm se zatím nespustil, ale pokud se pokusíš odejít, kamery tě zachytí a alarm se spustí.\r\nTvá situace má následky: můžeš se pokusit minihru znovu zahrát, ale část tvých peněz bude odečtena, nebo se rozhodnout misi ukončit a vzdát další postup.",
                            FailureTitle = "Nepodařilo se deaktivovat kamery",
                            RoomId = 3,
                            SuccessSubtitle = "Čistý průchod zajištěn",
                            SuccessText = "Zvládl jsi to perfektně. Poslední kód jsi opsal včas a systém ho okamžitě potvrdil. Odpočet zmizel, obraz na kamerách zčernal a kontrolky signalizují úplné vypnutí sledování. Žádný alarm, žádné komplikace. Cesta ven je teď bezpečná a kamery už ti stát v cestě nebudou.",
                            SuccessTitle = "Kamery deaktivovány"
                        },
                        new
                        {
                            Id = 4,
                            FailureSubtitle = "Ověření selhalo",
                            FailureText = "Dodatečné ověření se nepodařilo dokončit. Systém tvou identitu nepotvrdil a použití hlavního PINu bylo zablokováno. Bez tohoto PINu zůstávají hlavní dveře banky uzamčené a není možné pokračovat dál v tvé misi.\r\nDůsledky jsou jasné: můžeš se pokusit minihru znovu zahrát a opravit svůj neúspěch, nebo se rozhodnout vzdát celou misi a ukončit postup.",
                            FailureTitle = "PIN nebyl rozluštěn",
                            RoomId = 4,
                            SuccessSubtitle = "Přístup potvrzen",
                            SuccessText = "Dodatečné ověření proběhlo úspěšně a systém potvrdil tvou identitu. Použití hlavního PINu k odemčení hlavních dveří banky bylo povoleno. Zapamatuj si tento PIN, budeš ho potřebovat při dalším kroku, protože bez něj se hlavní dveře neotevřou a v postupu nebude možné pokračovat.",
                            SuccessTitle = "PIN získán!"
                        },
                        new
                        {
                            Id = 5,
                            FailureSubtitle = "Bohužel jsi nedokázal správně zastavit čísla včas",
                            FailureText = "S napětím sleduješ, jak se poslední číslice zastavuje, ale bohužel ne na správné hodnotě. Čas vypršel dříve, než ses stihl trefit do všech správných čísel, nebo jsi udělal příliš mnoho chyb při jejich zastavování. Hlavní dveře zůstávají pevně zamčené a tvůj pokus o únik selhal.\r\nNyní stojíš před rozhodnutím, jak dál pokračovat. Můžeš se pokusit minihru zopakovat, i když tě to bude stát část peněz, nebo ukončit misi a vzdát se mise.",
                            FailureTitle = "Únik selhal – Dveře zůstávají zamčené",
                            RoomId = 5,
                            SuccessSubtitle = "Gratulujeme k úspěšnému úniku z banky!",
                            SuccessText = "S napětím sleduješ, jak se poslední číslice zastavuje přesně na správné hodnotě. Jakmile všechny sloupce ukazují cílovou kombinaci, ozve se tiché cvaknutí. Hlavní dveře se pomalu otevírají, odhalující cestu ven do svobody. Únik je dokončen! S úlevou a triumfem opouštíš budovu, vědom si toho, že jsi úspěšně zvládl všechny výzvy a unikl bez povšimnutí.",
                            SuccessTitle = "Dveře odemčeny – Únik úspěšný!"
                        });
                });

            modelBuilder.Entity("unikovahra.Server.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroSubtitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "/images/room1.jpg",
                            IntroSubtitle = "Tvým úkolem je správně přesměrovat elektrickou energii v rozvaděči.",
                            IntroText = "Na panelu vidíš několik šipek, které jsou náhodně otočené. Kliknutím na šipku ji vždy otočíš o 90°.\r\nNež vyprší čas, musíš z těchto šipek vytvořit souvislou trasu od startu až do cíle.\r\n",
                            IntroTitle = "Nefunguje proud! Zprav to!",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "/images/room2.jpg",
                            IntroSubtitle = "Tvým úkolem je si zamapatovat světelnou kombinaci pro otevření dvěří",
                            IntroText = "Na displeji se objeví mřížka tlačítek, která se v náhodném pořadí rozsvěcí. Ty musíš sekvenci zopakovat klikáním na správná tlačítka.",
                            IntroTitle = "Teď se musíš dostat do kanclu",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "/images/room3.jpg",
                            IntroSubtitle = "Tvým úkolem je rychle opsat text výše zobrazený pro vypnutí kamer",
                            IntroText = "Pokoušíš nabourat do interního systému banky. Na obrazovce se objeví odpočet a několik kódů, které je nutné přesně opsat. Pokud se ti to nepovede tak příjdeš o pár peněz",
                            IntroTitle = "Vypni kamery! Rychle!",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "/images/room4.jpg",
                            IntroSubtitle = "Tvým úkolem je posouvat bankovky aby byly číselně seřazené",
                            IntroText = "Cílem je pomocí posouvání dlaždic seřadit bankovky do správného pořadí. Princip funguje stejně jako klasická „Patnáctka“.",
                            IntroTitle = "Našel jsi další box s penězi",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "/images/room5.jpg",
                            IntroSubtitle = "Tvým úkolem je zastavit číslo na tom, které bylo zmíněné v dřívějších minihrách",
                            IntroText = "Na displeji běží několik sloupců s čísly 0–9, která se nepřetržitě posouvají shora dolů. Úkolem je kliknutím zastavit každý sloupec přesně na hodnotě, která je určena v cílové kombinaci.",
                            IntroTitle = "Odemkni dveře a zdrhej!",
                            Order = 5
                        });
                });

            modelBuilder.Entity("unikovahra.Server.Models.StoryNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("NextA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NextB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionA")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionB")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StoryNodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Header = "Únik z trezoru",
                            ImageUrl = "/images/img6.jpg",
                            NextA = 2,
                            NextB = 3,
                            OptionA = "Vzít tašku s nářadím",
                            OptionB = "Hledat vypínač sirény",
                            Text = "Siréna řve pronikavým, nekonečným tónem. Červené světlo bliká v pravidelných intervalech a vrhá po stěnách trezoru roztřesené stíny. Hlava bolí. Paměť se vrací pomalu.\r\nDostal ses dovnitř, teď jsi uvnitř hlavního trezoru banky. Vloupání mělo být rychlé, čisté a bezhlučné, jako vystřižené z filmu. Něco se však strašlivě pokazilo."
                        },
                        new
                        {
                            Id = 2,
                            Header = "Stín a taška",
                            ImageUrl = "/images/scene1.jpg",
                            NextA = 4,
                            NextB = 5,
                            OptionA = "Šokovou pistoli",
                            OptionB = "Radiovou rušičku",
                            Text = "Konečně jsi u tašky, plné tvého specializovaného nářadí. Rychle ji prohrabuješ. V tom zaslechneš tiché, pravidelné kroky přicházející z chodby, přímo k masivním dveřím trezoru. Musíš se rozhodnout a jednat. Už se nejedná jen o tiché proniknutí, ale o přímou konfrontaci nebo únik. Co vytáhneš z tašky, abys získal kritickou výhodu?"
                        },
                        new
                        {
                            Id = 3,
                            Header = "Hledání blokace",
                            ImageUrl = "/images/scene1.jpg",
                            NextA = 5,
                            NextB = 4,
                            OptionA = "Použít hák a lano",
                            OptionB = "Vylézt po schránkách",
                            Text = "Prohledáváš studené kovové stěny trezoru a horečně hledáš nouzové ovládání, které by mohlo sirénu umlčet. Nad sebou, vysoko u stropu, konečně spatříš malou, nenápadnou skříňku s nápisem EMERGENCY OVERRIDE. Dostaneš se k ní jen stěží. Je to tvoje poslední šance, než dorazí ochranka."
                        },
                        new
                        {
                            Id = 4,
                            Header = "Setkání v temnotě",
                            ImageUrl = "/images/scene1.jpg",
                            NextA = 7,
                            NextB = 6,
                            OptionA = "Zaútočit ve tmě",
                            OptionB = "Aktivovat oslňujicí přístroj",
                            Text = "Ať už jsi vylezl na schránky, nebo vytáhl pistoli, nastalo rychlé vypnutí světel. Dveře trezoru se s hlasitým zasyčením otevírají jen na škvíru, ale pak se zaseknou. Jsi v hluboké, dezorientující tmě. Cítíš, že někdo je blízko, ale nevidíš nic. Je tu příliš horko. Slyšíš jen pomalé, těžké dýchání před sebou. Máš v kapse přístroj, který by mohl vydat oslňující záblesk."
                        },
                        new
                        {
                            Id = 5,
                            Header = "Panika a pečetění",
                            ImageUrl = "/images/scene1.jpg",
                            NextA = 6,
                            NextB = 7,
                            OptionA = "Podklouznout pod dveřmi",
                            OptionB = "Schovat se mezi penězi",
                            Text = "Tvůj poslední manévr (ať už rušička, nebo hák) spustil sekundární bezpečnostní protokol. Celý trezor se začal \r\ns ohlušujícím rachotem otřásat a dveře se začaly zvenčí  automaticky zavírat. Systém tě považuje za hrozbu a snaží se trezor zapečetit. Máš jen milisekundy na to, abys reagoval, než se masivní ocelová deska plně zasune."
                        },
                        new
                        {
                            Id = 6,
                            Header = "Chycen!",
                            ImageUrl = "/images/scene1.jpg",
                            NextA = 1,
                            OptionA = "Restart",
                            Text = "Ať už jsi proklouzl, nebo aktivoval přístroj, bylo pozdě. Světla se prudce rozsvítila a kolem tebe okamžitě stojí tým bankovní ostrahy. Cítíš, jak ti jeden z nich chytil ruku a na zápěstích ti zacvakla studená pouta. Tvoje dobrodružství končí. Systém zvítězil.\r\n\r\nMisi se nepovedlo dokončit."
                        },
                        new
                        {
                            Id = 7,
                            Header = "Tma v trezoru",
                            ImageUrl = "/images/scene1.jpg",
                            OptionA = "Začít sbírat",
                            Text = "Tvůj zoufalý pokus selhal. S ohlušujícím kovovým ŽUCH zapadla poslední západka a dveře se zaseknuly. Siréna umlkla. Červené nouzové světlo přestalo blikat, což přineslo totální, absolutní tmu.\r\n\r\nNikdo tě nevidí. Nikdo tě neruší. Máš teď nečekaně všechno ticho a soukromí světa, abys splnil to, pro co jsi přišel. Sáhneš pro chladné, čisté bankovky a začínáš je vkládat do tašky."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
